# Generated by Django 5.2.7 on 2025-11-26 00:33

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0016_alter_chatgroup_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='chat_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
