# Generated by Django 5.2.7 on 2025-11-25 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_folowerscount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folowerscount',
            name='folower',
        ),
        migrations.AddField(
            model_name='folowerscount',
            name='folowers',
            field=models.ManyToManyField(related_name='folowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
