# Generated by Django 5.2.7 on 2025-11-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0006_folowers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folowers',
        ),
    ]
