# Generated by Django 5.2.7 on 2025-11-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0011_profile_folowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='folowing',
        ),
    ]
