# Generated by Django 5.2.7 on 2025-11-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0016_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
