# Generated by Django 5.2.7 on 2025-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0017_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts_images/'),
        ),
    ]
